### ISSUE TITLE
todo omnibus

### ISSUE THREAD

**Issue by chrisguida** [chrisguida/watchdescriptor#4]
- [ ] fix spends to external accounts
  - [ ] differentiate between received txs (no prevouts owned), spent txs (all prevouts owned) and shared txs
    - [ ] mark as exception, warn user, prompt them to fix
    - [ ] rpc tools for manually fixing exceptions
- [ ] implement backend based on CLN config
- [ ] remember wallets in datastore
  - [ ] remember wallet state in datastore
- [ ] birthday/gap? defaults
- [ ] rpc command to rescan (for later)
- [ ] implement bitcoind backend?

**Comment by chrisguida** [comment]
Replaced by issues 4-10
